export const ERROR_CODES = Object.freeze({
  // Generic
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",

  // Auth & Identity
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",

  // Business Domain
  BUSINESS_NOT_FOUND: "BUSINESS_NOT_FOUND",
  BUSINESS_ALREADY_EXISTS: "BUSINESS_ALREADY_EXISTS",
  BUSINESS_UNVERIFIED: "BUSINESS_UNVERIFIED",
  VERIFICATION_IN_PROGRESS: "VERIFICATION_IN_PROGRESS",

  // Payments & Membership
  PAYMENT_FAILED: "PAYMENT_FAILED",
  MEMBERSHIP_EXPIRED: "MEMBERSHIP_EXPIRED",

  // Leads & Enquiries
  ENQUIRY_NOT_FOUND: "ENQUIRY_NOT_FOUND",
  LEAD_NOT_FOUND: "LEAD_NOT_FOUND",
});
