export const ENUMS = Object.freeze({
  MEMBERSHIP_TIERS: ["Free", "Basic", "Premium", "Enterprise"],
  BUSINESS_TYPES: [
    "Proprietorship",
    "Partnership",
    "LLP",
    "Private Limited",
    "Public Limited",
    "Trust / NGO",
  ],
  CATALOGUE_TYPES: ["Product", "Service"],
  EVENT_MODES: ["In-person", "Online", "Hybrid"],
  NOTIFICATION_TYPES: [
    "Lead",
    "Enquiry",
    "Message",
    "Membership",
    "Payment",
    "Event",
    "Review",
    "Account",
    "Verification",
    "System",
    "General",
  ],
  PAYMENT_METHODS: ["Card", "Bank transfer", "UPI", "Net Banking"],
  AUDIT_ACTIONS: [
    "CREATE",
    "UPDATE",
    "DELETE",
    "LOGIN",
    "LOGOUT",
    "VERIFY_APPROVE",
    "VERIFY_REJECT",
    "VERIFY_CORRECTION",
    "LEAD_ROUTE",
    "PAYMENT_COMPLETE",
  ],
});
